### ISSUE TITLE
View occurrences fails

### ISSUE THREAD

**Issue by rettinghaus** [pfefferniels/probstuecke-digital#120]
Trying to "view occurrences" in the bibliography throws this: 

> failed fetching references SyntaxError: The string did not match the expected pattern

**Comment by pfefferniels** [comment]
right, I will investigate!

**Comment by pfefferniels** [comment]
It works now. However, there seem to be duplicate entries …

**Comment by pfefferniels** [comment]
Which is fixed now as well. Closing therefore
