### ISSUE TITLE
How to deal with Probstück 24?

### ISSUE THREAD

**Issue by pfefferniels** [pfefferniels/probstuecke-digital#20]
In the very long text on (or better: following) the 24th Probstück Mattheson reflects, just like in the "Vorbereitung zur Organisten-Probe", about all sort of things (temperature, notation problems etc.), but says nearly nothing about the Probstück itself. To which extent should we or shouldn't we reproduce this text?

**Comment by rettinghaus** [comment]
A critical edition should always be complete.
