### ISSUE TITLE
IIIF support

### ISSUE THREAD

**Issue by pfefferniels** [pfefferniels/probstuecke-digital#23]
Currently, all facsimile files are stored on the `public/facsimile` folder. All references between facsimiles images and the transcriptions are stored in the `annotations_{1st|de}.tei file`.

It would be good to structure the facsimile data in a better way:

1. MEI files contain their own facsimile references as music is concerned
2. TEI files contain their own facsimile references as text is concerned
3. Additionally, an AnnotationList service is provided that keeps the combined data of (1) and (2) as IIIF annotations

An annotation on a whole page of music might look like this:

```
    {
      "@context": "http://iiif.io/api/presentation/2/context.json",
      "@id": "https://probstuecke-digital.de/iiif/1/annotation/facsimile_de-p386",
      "@type": "oa:Annotation",
      "motivation": "sc:painting",
      "resource": {
        "@id": "http://probstuecke-digital.de/iiif/1/score.mei#xpointer(//pb[n='386'])",
        "@type": "dctypes:Image",
        "format": "application/mei+xml"
      },
      "on": "https://api.digitale-sammlungen.de/iiif/presentation/v2/bsb10598495/canvas/386"
    },
```
 
Or an annotation on a measure of music:

```
    {
       "@context": "http://iiif.io/api/presentation/2/context.json",
       "@id": "https://probstuecke-digital.de/iiif/1/annotation/facsimile_de-measure1",
       "@type": "oa:Annotation",
       "motivation": "sc:painting",
       "resource": {
         "@id": "http://probstuecke-digital.de/iiif/1/score.mei#xpointer(//staff[xml:id='m-40'])",
         "@type": "dctypes:Image",
         "format": "application/mei+xml"
       },
       "on": "https://api.digitale-sammlungen.de/iiif/presentation/v2/bsb10598495/canvas/386#xywh=175,134,439,185"
     }
```
And of course annotations on the text ...

Any comments/suggestions? @rettinghaus ?

**Comment by rettinghaus** [comment]
Basically it looks good to me. On the other hand, there's way to much information here, that may be redundant. 
If we have something like this:
```xml
<graphic target="bsb10598495_00440.jpg" width="1998" height="2477"/>
<zone type="measure" ulx="105" uly="260" lrx="545" lry="800"/>
```
we could generate all we need (or want to provide) from this data:
https://api.digitale-sammlungen.de/iiif/presentation/v2/bsb10598495/canvas/440#xywh=105,260,440,540
or
https://api.digitale-sammlungen.de/iiif/image/v2/bsb10598495_00440/105,260,440,540/full/0/default.png

Or am I missing something?
