### ISSUE TITLE
combine pointers

### ISSUE THREAD

**Issue by rettinghaus** [pfefferniels/probstuecke-digital#26]
Instead of splitting references up into different pointers, like in Prob-Stück 10: 
```xml
<ref target="m-35">Die</ref> <ref target="m-57">erste</ref>
<ref target="m-80">Zeile</ref> <ref target="m-105">dieses</ref>
<ref target="m-128">Stückes</ref> spielet man
```
we could use `<annot>` in the MEI to collect all members with a `@plist` and point directly to the annotation, like: 
```xml
<annot xml:id="annot-01" @plist="#m-35 #m-57 #m-80 #m-105 #m128" @label="Mattheson's first remark"></annot>
```

**Comment by pfefferniels** [comment]
Yes, but I guess it would add a lot of complexity to render it properly, especially since verovio won't include `<annot>`  in the rendered SVG.

**Comment by rettinghaus** [comment]
annot will turn up in the SVG but we loose all non-textual information there. 
I was thinking of this:
On click look up in the MEI file which IDs are involved and highlight those in the SVG.

**Comment by rettinghaus** [comment]
`@target` in TEI can hold multiple occurrences: https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-att.pointing.html
Could we make use of this?

**Comment by pfefferniels** [comment]
Yes, that is certainly the best options, thanks!

**Comment by rettinghaus** [comment]
ongoing effort, closing for now.
