### ISSUE TITLE
What about Mattheson's remarks?

### ISSUE THREAD

**Issue by rettinghaus** [pfefferniels/probstuecke-digital#44]
Following some Prob-Stücke there is a remark by Mattheson, especially that one below PS8. How to deal with those? Where should they be encoded and how? 
(In the PS8 case we would then have two `key-overlay`s)

**Comment by pfefferniels** [comment]
Perhaps using the [group element](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-group.html)? So we'd have something like:

```
  <text>
    <group>
      <group source="#orchestre1713">
        <text>
          <body>
            <p xml:id="on-meter-signature">
              <!-- description from Das neu-eröffnete Orchestre -->
            </p>
          </body>
        </text>
        <text>
          <body>
            <p xml:id="on-key-signature">
              <!-- description from Das neu-eröffnete Orchestre -->
            </p>
          </body>
        </text>
      </group>
      
      <group source="#firstEdition">
        <text>
          <body>
            <p>
              <!-- description from below the PS -->
            </p>
          </body>
        </text>
        <text>
          <body>
            <div>
              <head>Erläuterungen</head>
              <!-- The Erläuterungen themselves -->
            </div>
          </body>
        </text>
      </group>
    </group>
  </text>
```
I'm not sure about proper IDs for the overlays though, something like a `class` attribute would be more appropriate ...

**Comment by pfefferniels** [comment]
@rettinghaus ?

**Comment by rettinghaus** [comment]
Seems a bit too structured for now. I'll think about this.

**Comment by pfefferniels** [comment]
Those remarks are encoded now in a `tei:div` in the comment files. Key and meter characteristics are separated out.
