### ISSUE TITLE
beginnings vs. breaks

### ISSUE THREAD

**Issue by rettinghaus** [pfefferniels/probstuecke-digital#60]
While in DTA-BF `<pb>` marks the beginning of a page, `<lb>` is used at the end of a line. 
The TEI Guidelines now make it very clear that it should be used to mark the beginning of a line. We should follow the TEI Guidelines.

See:
https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-pb.html
https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-lb.html
and
https://github.com/deutschestextarchiv/dtabf/issues/33

**Comment by pfefferniels** [comment]
We are following the TEI guidelines and documented the decision, therefore closing.
