### ISSUE TITLE
displaying Mattheson's annotations 

### ISSUE THREAD

**Issue by rettinghaus** [pfefferniels/probstuecke-digital#75]
In some pieces (e.g. PS11) there are annotations by Mattheson in the left hand. These too shouldn't be displayed by default in the edition. That can be achieved by XSLT easily. Question is: how to encode it in a good way?

**Comment by pfefferniels** [comment]
Currently, it's encoded in a similiar way as the additional staff for annotations: a `layerDef` with an xml:id set to `layer-mattheson` defines the `n` of all the layers that are part of the annotations. Would you agree? The referenced commit hides those layers by default ...

**Comment by rettinghaus** [comment]
`<layerDef>` sounds good. I'm just wondering if the `@xml:id` approach is the way to go.

**Comment by pfefferniels** [comment]
`@type` perhaps …?

**Comment by rettinghaus** [comment]
Using `@type` for this sounds reasonable.
