### ISSUE TITLE
Merge first and second edition

### ISSUE THREAD

**Issue by pfefferniels** [pfefferniels/probstuecke-digital#79]
Ist [das](https://github.com/pfefferniels/probstuecke-digital/blob/experimental-merge/data/3/mattheson/comments.xml) der "way to go"? Ich denke, der Erkenntnisgewinn ist deutlich größer als einfach stumpf Erst- und Zweitausgabe separat zu kodieren. Ist aber zugleich ziemlich aufwendig ...

**Comment by rettinghaus** [comment]
Theoretisch ja ;-) Aber ich finde es etwas overkill. Sinnvoller (und übersichtlicher) wäre es vermutlich ganze Absätze gegenüber zu stellen. 
Ich denke, das sollten wir auf später verschieben und erstmal die Noten fertigstellen, da sind wir in diesem Punkt weiter.

**Comment by pfefferniels** [comment]
closing it for now
