### ISSUE TITLE
Word breaks

### ISSUE THREAD

**Issue by pfefferniels** [pfefferniels/probstuecke-digital#83]
I'd like to propose using `<pc force="weak">-</pc>` for the hyphens at line breaks (as [suggested by the TEI guidelines](https://tei-c.org/release/doc/tei-p5-doc/en/html/CO.html#COPU-2)). This could be added by a simple regex on all the TEI documents. I don't feel very good about the regex replacements by JS everytime a Probstück is loaded … 
This would allow us to simply hide linebreaks by CSS: `tei-pc[@force='weak'] { display: none } ` and `tei-lb { display: none }`

**Comment by pfefferniels** [comment]
@rettinghaus do you have an opinion on this? [Here](https://edition-humboldt.de/richtlinien/frameworks/basis/text/zeilenumbruch.html) hyphens at line breaks are also encoded (but using `<g>` instead of `<pc>` ...)

**Comment by rettinghaus** [comment]
No project has figured out a perfect solution for this. `<pc>` isn't mentioned in `DTABf`. `<g>` *is* mentioned, but strictly ruled out …
And the TEI Guidelines say, that `<g>`
> represents a glyph, or a non-standard character

Do you think, changing this would improve anything?

**Comment by pfefferniels** [comment]
I don't have a strong opinion on this, but those lines
```
  if ($('#ignore-lb').is(':checked')) {
    const lbWithHyphen = /\-(\n|\s)*<lb(\s)*\/>([a-z]|ſ)/g;
    teiComments = teiComments.replace(lbWithHyphen, '$3&#xAD;');
    keyCharacteristics = keyCharacteristics.replace(lbWithHyphen, '$3&#xAD;');
    meterCharacteristics = meterCharacteristics.replace(lbWithHyphen, '$3&#xAD;');

    await Promise.all([renderComments(), renderKeyOverlay(), renderMeterOverlay()]);
    $('tei-lb').hide();
  } else {
    const softHyphen = /\&#xAD;/g;
    teiComments = teiComments.replace(softHyphen, '-<lb/>');
    keyCharacteristics = keyCharacteristics.replace(softHyphen, '-<lb/>');
    meterCharacteristics = meterCharacteristics.replace(softHyphen, '-<lb/>');

    await Promise.all([renderComments(), renderKeyOverlay(), renderMeterOverlay()]);
    $('tei-lb').show();
  }
```
do not only take quite some time – each time a page gets loaded, for hiding line breaks is activated by default, but also don't function very reliably.

**Comment by pfefferniels** [comment]
Using now the DTAs CAB service to turn the textes into their modern forms, including hyphenation. This happens automatically before deploying. It is for sure the best way to cover all kinds of corner cases.
