### ISSUE TITLE
Move data to separate repo

### ISSUE THREAD

**Issue by pfefferniels** [pfefferniels/probstuecke-digital#87]
As discussed some time ago, I'd like to start moving the MEI/TEI encodings into a separate repository, that we can include as a git submodule. Are there any objections, hints, comments?

**Comment by rettinghaus** [comment]
I wondered what the main repo should be, and if the data is the central object. But I think it totally makes sense to have the "application" together in one repo and "loading" the data from somewhere else. So yes please, go ahead.

**Comment by pfefferniels** [comment]
I think, the data should be the central object. Our guidelines say at the moment: "This encoding […] builds the core of the edition, which then can be visualised with appropriate software." – which somehow goes is that direction. See also the  Guidelines of the [Digital Mozart Edition]("https://dme.mozarteum.at/musik/edition/"): "Die Codierung ist die Edition."
