### ISSUE TITLE
choose special font for comments

### ISSUE THREAD

**Issue by rettinghaus** [pfefferniels/probstuecke-digital#96]
Bootstrap resets non-serif fonts system-specific differently, making some glyphs we use in the edition look ugly. We should look for a good font we can use at least for the comments. 

This one looks promising, but should be tested thoroughly: https://fonts.google.com/specimen/Scada

**Comment by pfefferniels** [comment]
How about [Junicode](https://de.wikipedia.org/wiki/Junicode)? It natively supports the special characters we need and it's used in the DTAoX framework ...

**Comment by pfefferniels** [comment]
That's how it looks like with Junicode:

![grafik](https://user-images.githubusercontent.com/47777840/110203172-d761a300-7e6c-11eb-88fb-e1ed9dcf6094.png)

**Comment by rettinghaus** [comment]
Looks great!

**Comment by pfefferniels** [comment]
closed with pfefferniels/probstuecke-react@c00c1d1
